server:
  port: 8888
  timeout: 120s
  sleep: 10s

network: testnet

fullnode:
  btc:
    rpcs:
      - rpc_url:
        rpc_user:
        rpc_pass:
    confirmations: 1
  eth:
    rpcs:
      - rpc_url:
    confirmations: 4

chains: [btc, eth]

